apiVersion: v1
kind: Secret
metadata:
  name: proseed-aws-credentials
  namespace: proseed
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: 'aws-credentials/proseed-aws-credentials'
type: Opaque
