---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: proseed
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBzdSCtw1k+Zwy6tW57Ofh63pijXv6iNuctbGd5K/27pReAx+j9ZEQsFt2ch+xiJdadPMg13jEhVmnEu4jzljCRt10MyV8Bp7dxlFCABCWi2iKU0KeKesyH4c943DPDWbFet6eIQIxiN9euSPy1UqPxu1RnolFMbuC9JwEyQdv4qNUj5CdWESlw1H7/EQIphcvER3+H4H5u4SmKpUi7z1Jzs5YAZf6+qWyXXWdQvyfIaWOeYVLc0ZGdi7MS+2b/yXp7wzefN2gtR/VR/1dxbGvhZgTf/vyd4ZHimn2a1Fkw+TgrQh/rizQZeI7wC2ipHoFm6JHfZjBvH8Pw5RSQK5/6H1/vfrhr/ble9Sq6/fmrGclqBqWeaB5aRJ77Z3EWUChW+DMmLSR79wU7JFG8P9q1PH7IFNKCEvICYweIc8NUuMSM/ANkEwwvHr5Yrqym1ot+GAW+rcMW/AStO6opLkZKks24yMlgJ6txo96h/cBB+IrBOGOB6gC75J+QnTWyqKopJYUFCuhb9G91WXzHUnM2+N0EO2UEpFivzlTYd0q7TkV9wqi21fVLp709bPdH2BoY/rQhENGvRIvlQfFS7QIzqzeZy15Wj2nix5UEsUbbyDQifQXZGfi/8B78Nvlq8rCXoTD80tGorK5CTJuCbO3s2+w9St1hWZERm9OvJ8uFY7TdnIu4661Gk6OeGS5YBvyp3URDbPlUWyQCNcc6XAWq7QD+cQ==
    AWS_SECRET_ACCESS_KEY: AgC6ZOR7YLpfdlw2rXzUVXu5HuihgVZAJc/1m89hmt8V+FcfZiOIvq/6TvbyjCkWLS7xzQkwbe/jy7HDTZOA7Lwgjz/tcVeWKeafiiYbejBS7fktVmNA0GRuuHeVYhCNraRXpF7VUyc1XnEZdNtjt2Smh7XBmiSaqHbWED/5a8CNIqw5uVt16ZUY/S51HrccdP1B1/ud9Mtj51nkYqOm/lTvzZM7GuTO6VVW7tZfk/vbdrxE02UQ6TeH5+z2B+6uhk85wOw/TOfDEP5jnnAR83mPsNQDSyZUykQYAjV/DXSYpnOPZ773Zw6BOosCsYXyqPA1cm/3W8zquCStwUFrRPgZ5fhnn5L7h818zmh/JUpR3YqdFJVaCADNYA2Vyt5A83bSql/NE3sDeU6Wk32AufLz2WhuaGTAkaeGzxhnZB46WWwNO4vMXq6mtSWggSXDgBJ4lXY6/4+/zo9tiuDCMKCnkNBZE4ZHMdfx7Vf/oGhWhy0bgA7yjL4ZuJU62cnAYO5SFxVJrrsjCUtGJZotLLZYD9wPf/0OFsstq1w3FOsXj1I5Mnj8IBXUpMbev07nRHaRcgSOfU8+AKki68WSLMGAfGNiLIF5UIosi+F1fRs5hIl8C5W7eicTdDIMCIgJcaZr+e7i33SLhFTWJ4U7l1k0eX7locVE/er5DLcCVQCcR6IOudR/zJTVBQ/IE7gNd1C4bTpNOyVDbMp9Vaj0owRk9HFX1DfX+ZYsVnAV5ij3j6CrdBKv/OFv
  template:
    metadata:
      name: aws-credentials
      namespace: proseed
    type: Opaque
