apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
  namespace: proseed
data:
  # MEDIA_BUCKET_NAME: 'proseed-media'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://simplest-collector.observability.svc.cluster.local:4317'
