apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
  namespace: proseed
data:
  AWS_REGION: 'ap-northeast-2'
  S3_BUCKET_NAME: 'proseed-uploads'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://simplest-collector.observability.svc.cluster.local:4317'
