apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: proseed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: database-credentials
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@proseed-database.chmw24k2w9e7.ap-northeast-2.rds.amazonaws.com:5432/skkuding"
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-10503dc4-8257-466c-88a5-7ade0e1f5da6
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-10503dc4-8257-466c-88a5-7ade0e1f5da6
        property: password
