apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proseed

resources:
  - aws-credentials.yaml
  - configmap.yaml
  - deployment.yaml
  - external-secret.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
