apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
  namespace: proseed
data:
  # NEXT_PUBLIC_ envs are injected during Next.js build phase
  # https://nextjs.org/docs/app/guides/environment-variables#bundling-environment-variables-for-the-browser
  NEXT_URL: 'https://proseed.lab.skkuding.dev'
  NEXTAUTH_URL: 'https://proseed.lab.skkuding.dev/next-auth/api/auth'
  MEDIA_BUCKET_NAME: 'proseed-media'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.proseednow.com'
