services:
  postgres:
    image: postgres:17-alpine
    container_name: proseed-db
    environment:
      POSTGRES_USER: proseed
      POSTGRES_PASSWORD: proseed
      POSTGRES_DB: proseed
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
